## Flags
flag_LQT: false
flag_a3: false
h: 0.02

# LQT Parameters
# Reference
Am:
  rows: 5
  cols: 5
  data: [
    0.999992870110446, -0.000712988288670474, -5.41441701278375e-08, -5.41441057874235e-06, 0.0,
    0.0199999524673852, 0.999992870110446, -3.60961305760057e-10, -5.41441701278375e-08, 0.0,
    0.000199999762336881, 0.0199999524673852, 0.999999999998195, -3.60961305760057e-10, 0.0,
    1.33333238268076e-06, 0.000199999762336881, 0.0199999999999928, 0.999999999998195, 0.0,
    6.66666349782453e-09, 1.33333238268076e-06, 0.000199999999999976, 0.0199999999999928, 1.0
  ]

Bm:
  rows: 5
  cols: 1
  data: [0.0, 0.0, 0.0, 0.0, 0.0]

Cmx:
  rows: 1
  cols: 5
  data: [9.0, 0.0, 0.2166, 0.0, 0.0005]

Cmy:
  rows: 1
  cols: 5
  data: [2.0000, -0.2095, 0.0713, -0.0095, 0.0005]

# LQT-I Parameters
# Reference
Am_LQTI:
  rows: 4
  cols: 4
  data: [
    0.999992870110446, -0.000712988288670474, -5.41441701278375e-08, -5.41441057874235e-06,
    0.0199999524673852, 0.999992870110446, -3.60961305760061e-10, -5.41441701278375e-08,
    0.000199999762336882, 0.0199999524673852, 0.999999999998195, -3.60961305760061e-10,
    1.33333238268077e-06, 0.000199999762336882, 0.0199999999999928, 0.999999999998195
  ]


Bm_LQTI:
  rows: 4
  cols: 1
  data: [0.0, 0.0, 0.0, 0.0]

Cmx_LQTI:
  rows: 1
  cols: 4
  data: [7.0, 0.0, 0.145340192222222, 0.0]

Cmy_LQTI:
  rows: 1
  cols: 4
  data: [0.0, -0.209466666666667, 0.0, -0.00947782589355556]

# Plant
# kp = 1.3
Ad:
  rows: 2
  cols: 2
  data: [1.0, 0.0197029776343279,
        0.0, 0.970445533548508]

Bd:
  rows: 2
  cols: 1
  data: [0.000297022365672118, 0.0295544664514918]

Cd:
  rows: 1
  cols: 2
  data: [1.0, 0.0]

## Initial Conditions - RL-LQT
# Reference
xm: [1.0, 0.0, 0.0, 0.0, 0.0]
xm_LQTI: [1.0, 0.0, 0.0, 0.0]

# Plant
x0x: [0.0, 0.0]
x0y: [0.0, 0.0]

## Gains
##LQT

Kx:
  rows: 1
  cols: 7
  data: [0.560095009012610, 0.274425596926665, -4.97251329502907, 0.0722338631828741, -0.120093534289683, 0.00131629297513977, -0.000303259154925205]

Ky:
  rows: 1
  cols: 7
  data: [0.560095009012681, 0.274425596926713, -0.971881804596493, 0.118598869314871, -0.0333046404090507, 0.00527061999274005, -0.000303259154925064]


    ## // Kx << 27.124426673138792, 5.368769229468123, -244.03576687339714, 0.6608225415608986, -5.8735890982539685, 0.012275805209641881, -0.01356221333656942; 
    ## // Kx << 27.1244266731466,	5.36876922946919,	-244.035798047837,	0.660572823817245,	-5.87468455619007,	0.0120130717500125,	-0.0146863131760855;


    ## // Ky << 27.1244266731349,	5.36876922946723,	-52.9208135832513,	5.68328558567109,   -1.87385859124528,  0.257034874578231,	-0.0146863131760852;
    
    ## LQTI
Kx_LQTI:
  rows: 1
  cols: 7
  ## data: [0.453100736264216, 0.224186363835759, -0.189780313098599, -0.0251683855364320, 0.000906742073633811, -0.000526099414870330, 1.65682396540503e-05]
  ## data: [0.4531, 0.2242, -0.1898, -0.0252, 0.0009, -0.0005, 0.0000]
  data: [0.928155355786142, 0.443739700504558, -0.429804239922965, -0.057723480611456, 0.001877193121614, -0.001204756500647, 3.424330119427803e-05]


Ky_LQTI:
  rows: 1
  cols: 7
  ## data: [0.453100736264347, 0.224186363835823, -0.189780313098619, 0.00191390775634247, 0.000820564853123855, 8.42221929107589e-05, 3.51868491685248e-05]
  ## data: [0.4531, 0.2242, -0.1898, 0.0019, 0.0008, 0.0001, 0.0000]
  data: [0.928155355786175, 0.443739700504576, -0.429804239922989, 0.003895803076313, 0.001846667364771, 1.730856931829058e-04, 8.012007475542086e-05]       

# =======================
# Constants
# =======================

## RL-LQT
kpx: 1.5
kpy: 1.5
ki: 10
Qe: 1
R: 1                  
K0factor: 1
gamma: 0.5


## LQTI
yss: 2
Qe_LQTI: 0.0001
